# Smartphone Drop

You work for a tech firm developing the newest smartphone that supposedly can survive falls from great heights. Your firm wants to advertise the maximum height from which the phone can be dropped without breaking.

You are given two of the smartphones and access to a 100-story tower from which you can drop either phone from whatever story you want. If it doesn’t break when it falls, you can retrieve it and use it for future drops. But if it breaks, you don’t get a replacement phone.

Using the two phones, what is the minimum number of drops you need to ensure that you can determine exactly the highest story from which a dropped phone does not break? 

We will denote n1 and n2 to be the number of drops from the first and second phones respectively. For our experiment we will drop the first phone at intervals greater than one until it breaks. When broken, we will move down to the last unbroken interval +1 and continue testing at intervals of 2. The total number of drops will be n1 + n2. The max height the phone can survive a fall is the floor below that.

$n = n_1 + n_2$

n2 is dependent on n1 in that n2 = 100/n1/2. n1 is dependent on the interval size (i). n1 = 100/i.

In [40]:
import numpy as np
i = np.arange(100)
i += 1
i

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [41]:
n1 = 100/i
n1



array([100.        ,  50.        ,  33.33333333,  25.        ,
        20.        ,  16.66666667,  14.28571429,  12.5       ,
        11.11111111,  10.        ,   9.09090909,   8.33333333,
         7.69230769,   7.14285714,   6.66666667,   6.25      ,
         5.88235294,   5.55555556,   5.26315789,   5.        ,
         4.76190476,   4.54545455,   4.34782609,   4.16666667,
         4.        ,   3.84615385,   3.7037037 ,   3.57142857,
         3.44827586,   3.33333333,   3.22580645,   3.125     ,
         3.03030303,   2.94117647,   2.85714286,   2.77777778,
         2.7027027 ,   2.63157895,   2.56410256,   2.5       ,
         2.43902439,   2.38095238,   2.3255814 ,   2.27272727,
         2.22222222,   2.17391304,   2.12765957,   2.08333333,
         2.04081633,   2.        ,   1.96078431,   1.92307692,
         1.88679245,   1.85185185,   1.81818182,   1.78571429,
         1.75438596,   1.72413793,   1.69491525,   1.66666667,
         1.63934426,   1.61290323,   1.58730159,   1.56

In [42]:
n2 = (100/n1/2 - 1)
n2

array([-0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,
        5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. ,
       21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5,
       27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. ,
       32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5,
       38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. ,
       43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5,
       49. ])

In [43]:
n = n1 + n2

In [44]:
n

array([99.5       , 50.        , 33.83333333, 26.        , 21.5       ,
       18.66666667, 16.78571429, 15.5       , 14.61111111, 14.        ,
       13.59090909, 13.33333333, 13.19230769, 13.14285714, 13.16666667,
       13.25      , 13.38235294, 13.55555556, 13.76315789, 14.        ,
       14.26190476, 14.54545455, 14.84782609, 15.16666667, 15.5       ,
       15.84615385, 16.2037037 , 16.57142857, 16.94827586, 17.33333333,
       17.72580645, 18.125     , 18.53030303, 18.94117647, 19.35714286,
       19.77777778, 20.2027027 , 20.63157895, 21.06410256, 21.5       ,
       21.93902439, 22.38095238, 22.8255814 , 23.27272727, 23.72222222,
       24.17391304, 24.62765957, 25.08333333, 25.54081633, 26.        ,
       26.46078431, 26.92307692, 27.38679245, 27.85185185, 28.31818182,
       28.78571429, 29.25438596, 29.72413793, 30.19491525, 30.66666667,
       31.13934426, 31.61290323, 32.08730159, 32.5625    , 33.03846154,
       33.51515152, 33.99253731, 34.47058824, 34.94927536, 35.42

In [45]:
np.ceil(min(n))

14.0

Therefore, the lowest number of drops you can have is 14.